### ISSUE TITLE
Request to Share Scripts Used for Figures in Your Article

### ISSUE THREAD

**Issue by yctaii** [marcowindt/passive-ckws-attack#1]
I recently came across your article titled "Passive query-recovery attack against secure conjunctive keyword search schemes" and was highly impressed by the charts and data visualizations you used in it.

In particular, I am quite interested in the scripts that you employed for creating those charts. I believe they could be of great help to my research project. Therefore, I would like to inquire whether you would be willing to share these chart scripts with me for use in my work.

I understand that these scripts may be your proprietary work or protected by copyright, and I will respect that. However, if it's possible, I would greatly appreciate your assistance.

My email address is yctai98@gmail.com. Thank you.

**Comment by marcowindt** [comment]
I received your email as well, but didn't have time yet to respond. I have added the jupyter notebooks I used to generate the figures I used in the paper to the repository. Beware, there's also a lot of noise in the notebooks due to me trying different stuff. Also, it may not be as readable.

Hope this will help in your research, good luck!
